### ISSUE TITLE
No metadata for DOIs with "(" or ")"

### ISSUE THREAD

**Issue by ivanhb** [opencitations/api#12]
It seems that for some DOIs which contain the characters "(" or ")", meta/v1/metadata returns no results.
e.g., 
https://opencitations.net/meta/api/v1/metadata/doi:10.1016/s0005-7894(77)80292-x

**Comment by eliarizzetto** [comment]
Other examples of DOIs for which the Meta API returns no results (although the resources exist in the triplestore):

10.1016/s0002-9610(00)00404-9
10.1016/s0188-4409(00)00147-8
10.1002/1096-8644(200103)114:3<224::aid-ajpa1022>3.3.co;2-9
10.1002/(sici)1098-2760(19990605)21:5<330::aid-mop7>3.3.co;2-e
10.1016/0005-2787(66)90121-3
10.1016/s0042-6989(00)00281-9
10.1016/s1386-1425(00)00293-6
10.1078/s1438-4639(04)70016-4
10.1016/s0006-3495(85)83809-1
10.1002/1097-0142(197805)41:5<1771::aid-cncr2820410519>3.0.co;2-c
10.1016/0022-1759(76)90032-6
10.1016/0005-2760(89)90213-0
10.1016/0360-3016(86)90170-7
10.1016/0014-2999(92)94830-o
10.1016/s0002-9394(98)00235-9
10.1016/0168-1656(90)90080-u
10.1016/0024-3205(94)90116-3
10.1016/0168-1656(90)90056-h
10.1016/0014-5793(73)80441-7

Notably, these DOIs work fine (i.e. return the correct results) when searched with OC _Index_ API (see e.g. [https://opencitations.net/index/api/v2/citations/doi:10.1016/s0002-9610(00)00404-9](https://opencitations.net/index/api/v2/citations/doi:10.1016/s0002-9610(00)00404-9)).
Decoding problems are likely related to Ramose.

**Comment by arcangelo7** [comment]
You're correct. The bug was indeed in the script called by Ramose to preprocess the SPARQL query, specifically in the use of `urllib.parse.quote` for literal values of identifiers inserted into the query. While there was likely a reason for its initial inclusion, removing it has resolved the issue without causing any apparent problems. All tests are now passing. The problem has been fixed in commit https://github.com/opencitations/api/commit/386571decd3b1b62165ee2db47b6f5bb6f711be2. I'll monitor for any potential future issues that may arise from this change, but for now, the solution appears to be effective
